// <auto-generated />
using System;
using ConverterAPI.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConverterAPI.Migrations
{
    [DbContext(typeof(AuditContext))]
    [Migration("20190611164958_MyCoreAPIDemo.Entities.AuditContext")]
    partial class MyCoreAPIDemoEntitiesAuditContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ConverterAPI.Entities.UserActions", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateTimeStamp")
                        .HasMaxLength(50);

                    b.Property<string>("FromUnit")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<double>("Initial")
                        .HasMaxLength(50);

                    b.Property<string>("ToUnit")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<double>("Value")
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.ToTable("UserAction","dbo");

                    b.HasData(
                        new
                        {
                            ID = new Guid("b53f5624-eeae-485d-83b6-e1cb73c7e001"),
                            DateTimeStamp = new DateTime(2019, 6, 11, 18, 49, 50, 25, DateTimeKind.Local).AddTicks(7783),
                            FromUnit = "KM",
                            Initial = 0.0,
                            ToUnit = "Mile",
                            Username = "Bob",
                            Value = 0.0
                        },
                        new
                        {
                            ID = new Guid("56d4d23a-aa4e-482d-89a4-9982ee5c439f"),
                            DateTimeStamp = new DateTime(2019, 6, 11, 18, 49, 50, 30, DateTimeKind.Local).AddTicks(4223),
                            FromUnit = "Mile",
                            Initial = 0.0,
                            ToUnit = "KM",
                            Username = "John",
                            Value = 0.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
